// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spark_query_result.proto

package com.viettel.bi.spark.thrift;

public final class SparkQueryResultMessage {
  private SparkQueryResultMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SparkQueryResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.viettel.bi.spark.thrift.SparkQueryResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    String getUsername();
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string ipAddress = 2;</code>
     * @return The ipAddress.
     */
    String getIpAddress();
    /**
     * <code>string ipAddress = 2;</code>
     * @return The bytes for ipAddress.
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();

    /**
     * <code>string sparkApp = 3;</code>
     * @return The sparkApp.
     */
    String getSparkApp();
    /**
     * <code>string sparkApp = 3;</code>
     * @return The bytes for sparkApp.
     */
    com.google.protobuf.ByteString
        getSparkAppBytes();

    /**
     * <code>string sessionId = 4;</code>
     * @return The sessionId.
     */
    String getSessionId();
    /**
     * <code>string sessionId = 4;</code>
     * @return The bytes for sessionId.
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>string thriftHost = 5;</code>
     * @return The thriftHost.
     */
    String getThriftHost();
    /**
     * <code>string thriftHost = 5;</code>
     * @return The bytes for thriftHost.
     */
    com.google.protobuf.ByteString
        getThriftHostBytes();

    /**
     * <code>int32 thriftPort = 6;</code>
     * @return The thriftPort.
     */
    int getThriftPort();

    /**
     * <code>string groupId = 7;</code>
     * @return The groupId.
     */
    String getGroupId();
    /**
     * <code>string groupId = 7;</code>
     * @return The bytes for groupId.
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <code>string statement = 8;</code>
     * @return The statement.
     */
    String getStatement();
    /**
     * <code>string statement = 8;</code>
     * @return The bytes for statement.
     */
    com.google.protobuf.ByteString
        getStatementBytes();

    /**
     * <code>string state = 9;</code>
     * @return The state.
     */
    String getState();
    /**
     * <code>string state = 9;</code>
     * @return The bytes for state.
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>string plan = 10;</code>
     * @return The plan.
     */
    String getPlan();
    /**
     * <code>string plan = 10;</code>
     * @return The bytes for plan.
     */
    com.google.protobuf.ByteString
        getPlanBytes();

    /**
     * <code>string error = 11;</code>
     * @return The error.
     */
    String getError();
    /**
     * <code>string error = 11;</code>
     * @return The bytes for error.
     */
    com.google.protobuf.ByteString
        getErrorBytes();

    /**
     * <code>int64 startTime = 12;</code>
     * @return The startTime.
     */
    long getStartTime();

    /**
     * <code>int64 finishTimestamp = 13;</code>
     * @return The finishTimestamp.
     */
    long getFinishTimestamp();

    /**
     * <code>int64 duration = 14;</code>
     * @return The duration.
     */
    long getDuration();

    /**
     * <code>string durationFormatted = 15;</code>
     * @return The durationFormatted.
     */
    String getDurationFormatted();
    /**
     * <code>string durationFormatted = 15;</code>
     * @return The bytes for durationFormatted.
     */
    com.google.protobuf.ByteString
        getDurationFormattedBytes();
  }
  /**
   * Protobuf type {@code com.viettel.bi.spark.thrift.SparkQueryResult}
   */
  public static final class SparkQueryResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.viettel.bi.spark.thrift.SparkQueryResult)
      SparkQueryResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SparkQueryResult.newBuilder() to construct.
    private SparkQueryResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SparkQueryResult() {
      username_ = "";
      ipAddress_ = "";
      sparkApp_ = "";
      sessionId_ = "";
      thriftHost_ = "";
      groupId_ = "";
      statement_ = "";
      state_ = "";
      plan_ = "";
      error_ = "";
      durationFormatted_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SparkQueryResult();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SparkQueryResultMessage.internal_static_com_viettel_bi_spark_thrift_SparkQueryResult_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SparkQueryResultMessage.internal_static_com_viettel_bi_spark_thrift_SparkQueryResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SparkQueryResult.class, Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object username_ = "";
    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @Override
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IPADDRESS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object ipAddress_ = "";
    /**
     * <code>string ipAddress = 2;</code>
     * @return The ipAddress.
     */
    @Override
    public String getIpAddress() {
      Object ref = ipAddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ipAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string ipAddress = 2;</code>
     * @return The bytes for ipAddress.
     */
    @Override
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      Object ref = ipAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPARKAPP_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object sparkApp_ = "";
    /**
     * <code>string sparkApp = 3;</code>
     * @return The sparkApp.
     */
    @Override
    public String getSparkApp() {
      Object ref = sparkApp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sparkApp_ = s;
        return s;
      }
    }
    /**
     * <code>string sparkApp = 3;</code>
     * @return The bytes for sparkApp.
     */
    @Override
    public com.google.protobuf.ByteString
        getSparkAppBytes() {
      Object ref = sparkApp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sparkApp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSIONID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object sessionId_ = "";
    /**
     * <code>string sessionId = 4;</code>
     * @return The sessionId.
     */
    @Override
    public String getSessionId() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>string sessionId = 4;</code>
     * @return The bytes for sessionId.
     */
    @Override
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THRIFTHOST_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile Object thriftHost_ = "";
    /**
     * <code>string thriftHost = 5;</code>
     * @return The thriftHost.
     */
    @Override
    public String getThriftHost() {
      Object ref = thriftHost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        thriftHost_ = s;
        return s;
      }
    }
    /**
     * <code>string thriftHost = 5;</code>
     * @return The bytes for thriftHost.
     */
    @Override
    public com.google.protobuf.ByteString
        getThriftHostBytes() {
      Object ref = thriftHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        thriftHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THRIFTPORT_FIELD_NUMBER = 6;
    private int thriftPort_ = 0;
    /**
     * <code>int32 thriftPort = 6;</code>
     * @return The thriftPort.
     */
    @Override
    public int getThriftPort() {
      return thriftPort_;
    }

    public static final int GROUPID_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile Object groupId_ = "";
    /**
     * <code>string groupId = 7;</code>
     * @return The groupId.
     */
    @Override
    public String getGroupId() {
      Object ref = groupId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <code>string groupId = 7;</code>
     * @return The bytes for groupId.
     */
    @Override
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATEMENT_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile Object statement_ = "";
    /**
     * <code>string statement = 8;</code>
     * @return The statement.
     */
    @Override
    public String getStatement() {
      Object ref = statement_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        statement_ = s;
        return s;
      }
    }
    /**
     * <code>string statement = 8;</code>
     * @return The bytes for statement.
     */
    @Override
    public com.google.protobuf.ByteString
        getStatementBytes() {
      Object ref = statement_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        statement_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile Object state_ = "";
    /**
     * <code>string state = 9;</code>
     * @return The state.
     */
    @Override
    public String getState() {
      Object ref = state_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>string state = 9;</code>
     * @return The bytes for state.
     */
    @Override
    public com.google.protobuf.ByteString
        getStateBytes() {
      Object ref = state_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAN_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile Object plan_ = "";
    /**
     * <code>string plan = 10;</code>
     * @return The plan.
     */
    @Override
    public String getPlan() {
      Object ref = plan_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        plan_ = s;
        return s;
      }
    }
    /**
     * <code>string plan = 10;</code>
     * @return The bytes for plan.
     */
    @Override
    public com.google.protobuf.ByteString
        getPlanBytes() {
      Object ref = plan_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        plan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERROR_FIELD_NUMBER = 11;
    @SuppressWarnings("serial")
    private volatile Object error_ = "";
    /**
     * <code>string error = 11;</code>
     * @return The error.
     */
    @Override
    public String getError() {
      Object ref = error_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <code>string error = 11;</code>
     * @return The bytes for error.
     */
    @Override
    public com.google.protobuf.ByteString
        getErrorBytes() {
      Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 12;
    private long startTime_ = 0L;
    /**
     * <code>int64 startTime = 12;</code>
     * @return The startTime.
     */
    @Override
    public long getStartTime() {
      return startTime_;
    }

    public static final int FINISHTIMESTAMP_FIELD_NUMBER = 13;
    private long finishTimestamp_ = 0L;
    /**
     * <code>int64 finishTimestamp = 13;</code>
     * @return The finishTimestamp.
     */
    @Override
    public long getFinishTimestamp() {
      return finishTimestamp_;
    }

    public static final int DURATION_FIELD_NUMBER = 14;
    private long duration_ = 0L;
    /**
     * <code>int64 duration = 14;</code>
     * @return The duration.
     */
    @Override
    public long getDuration() {
      return duration_;
    }

    public static final int DURATIONFORMATTED_FIELD_NUMBER = 15;
    @SuppressWarnings("serial")
    private volatile Object durationFormatted_ = "";
    /**
     * <code>string durationFormatted = 15;</code>
     * @return The durationFormatted.
     */
    @Override
    public String getDurationFormatted() {
      Object ref = durationFormatted_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        durationFormatted_ = s;
        return s;
      }
    }
    /**
     * <code>string durationFormatted = 15;</code>
     * @return The bytes for durationFormatted.
     */
    @Override
    public com.google.protobuf.ByteString
        getDurationFormattedBytes() {
      Object ref = durationFormatted_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        durationFormatted_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ipAddress_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sparkApp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sparkApp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sessionId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(thriftHost_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, thriftHost_);
      }
      if (thriftPort_ != 0) {
        output.writeInt32(6, thriftPort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, groupId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(statement_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, statement_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, state_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(plan_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, plan_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, error_);
      }
      if (startTime_ != 0L) {
        output.writeInt64(12, startTime_);
      }
      if (finishTimestamp_ != 0L) {
        output.writeInt64(13, finishTimestamp_);
      }
      if (duration_ != 0L) {
        output.writeInt64(14, duration_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(durationFormatted_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, durationFormatted_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ipAddress_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sparkApp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sparkApp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sessionId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(thriftHost_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, thriftHost_);
      }
      if (thriftPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, thriftPort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, groupId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(statement_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, statement_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, state_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(plan_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, plan_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, error_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, startTime_);
      }
      if (finishTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, finishTimestamp_);
      }
      if (duration_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, duration_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(durationFormatted_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, durationFormatted_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SparkQueryResult)) {
        return super.equals(obj);
      }
      SparkQueryResult other = (SparkQueryResult) obj;

      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getIpAddress()
          .equals(other.getIpAddress())) return false;
      if (!getSparkApp()
          .equals(other.getSparkApp())) return false;
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
      if (!getThriftHost()
          .equals(other.getThriftHost())) return false;
      if (getThriftPort()
          != other.getThriftPort()) return false;
      if (!getGroupId()
          .equals(other.getGroupId())) return false;
      if (!getStatement()
          .equals(other.getStatement())) return false;
      if (!getState()
          .equals(other.getState())) return false;
      if (!getPlan()
          .equals(other.getPlan())) return false;
      if (!getError()
          .equals(other.getError())) return false;
      if (getStartTime()
          != other.getStartTime()) return false;
      if (getFinishTimestamp()
          != other.getFinishTimestamp()) return false;
      if (getDuration()
          != other.getDuration()) return false;
      if (!getDurationFormatted()
          .equals(other.getDurationFormatted())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + IPADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getIpAddress().hashCode();
      hash = (37 * hash) + SPARKAPP_FIELD_NUMBER;
      hash = (53 * hash) + getSparkApp().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + THRIFTHOST_FIELD_NUMBER;
      hash = (53 * hash) + getThriftHost().hashCode();
      hash = (37 * hash) + THRIFTPORT_FIELD_NUMBER;
      hash = (53 * hash) + getThriftPort();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + STATEMENT_FIELD_NUMBER;
      hash = (53 * hash) + getStatement().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
      hash = (37 * hash) + PLAN_FIELD_NUMBER;
      hash = (53 * hash) + getPlan().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + FINISHTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFinishTimestamp());
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDuration());
      hash = (37 * hash) + DURATIONFORMATTED_FIELD_NUMBER;
      hash = (53 * hash) + getDurationFormatted().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SparkQueryResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SparkQueryResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SparkQueryResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SparkQueryResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SparkQueryResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SparkQueryResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SparkQueryResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SparkQueryResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SparkQueryResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SparkQueryResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SparkQueryResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SparkQueryResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SparkQueryResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.viettel.bi.spark.thrift.SparkQueryResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.viettel.bi.spark.thrift.SparkQueryResult)
        SparkQueryResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SparkQueryResultMessage.internal_static_com_viettel_bi_spark_thrift_SparkQueryResult_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SparkQueryResultMessage.internal_static_com_viettel_bi_spark_thrift_SparkQueryResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SparkQueryResult.class, Builder.class);
      }

      // Construct using com.viettel.bi.spark.thrift.SparkQueryResultMessage.SparkQueryResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        username_ = "";
        ipAddress_ = "";
        sparkApp_ = "";
        sessionId_ = "";
        thriftHost_ = "";
        thriftPort_ = 0;
        groupId_ = "";
        statement_ = "";
        state_ = "";
        plan_ = "";
        error_ = "";
        startTime_ = 0L;
        finishTimestamp_ = 0L;
        duration_ = 0L;
        durationFormatted_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SparkQueryResultMessage.internal_static_com_viettel_bi_spark_thrift_SparkQueryResult_descriptor;
      }

      @Override
      public SparkQueryResult getDefaultInstanceForType() {
        return SparkQueryResult.getDefaultInstance();
      }

      @Override
      public SparkQueryResult build() {
        SparkQueryResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SparkQueryResult buildPartial() {
        SparkQueryResult result = new SparkQueryResult(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SparkQueryResult result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.username_ = username_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ipAddress_ = ipAddress_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sparkApp_ = sparkApp_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sessionId_ = sessionId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.thriftHost_ = thriftHost_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.thriftPort_ = thriftPort_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.groupId_ = groupId_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.statement_ = statement_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.state_ = state_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.plan_ = plan_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.error_ = error_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.startTime_ = startTime_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.finishTimestamp_ = finishTimestamp_;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.duration_ = duration_;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.durationFormatted_ = durationFormatted_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SparkQueryResult) {
          return mergeFrom((SparkQueryResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SparkQueryResult other) {
        if (other == SparkQueryResult.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getIpAddress().isEmpty()) {
          ipAddress_ = other.ipAddress_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getSparkApp().isEmpty()) {
          sparkApp_ = other.sparkApp_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getThriftHost().isEmpty()) {
          thriftHost_ = other.thriftHost_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getThriftPort() != 0) {
          setThriftPort(other.getThriftPort());
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getStatement().isEmpty()) {
          statement_ = other.statement_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (!other.getPlan().isEmpty()) {
          plan_ = other.plan_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          bitField0_ |= 0x00000400;
          onChanged();
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (other.getFinishTimestamp() != 0L) {
          setFinishTimestamp(other.getFinishTimestamp());
        }
        if (other.getDuration() != 0L) {
          setDuration(other.getDuration());
        }
        if (!other.getDurationFormatted().isEmpty()) {
          durationFormatted_ = other.durationFormatted_;
          bitField0_ |= 0x00004000;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                username_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                ipAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                sparkApp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                sessionId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                thriftHost_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                thriftPort_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                groupId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                statement_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                state_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                plan_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 90: {
                error_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              case 96: {
                startTime_ = input.readInt64();
                bitField0_ |= 0x00000800;
                break;
              } // case 96
              case 104: {
                finishTimestamp_ = input.readInt64();
                bitField0_ |= 0x00001000;
                break;
              } // case 104
              case 112: {
                duration_ = input.readInt64();
                bitField0_ |= 0x00002000;
                break;
              } // case 112
              case 122: {
                durationFormatted_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00004000;
                break;
              } // case 122
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object username_ = "";
      /**
       * <code>string username = 1;</code>
       * @return The username.
       */
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = getDefaultInstance().getUsername();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object ipAddress_ = "";
      /**
       * <code>string ipAddress = 2;</code>
       * @return The ipAddress.
       */
      public String getIpAddress() {
        Object ref = ipAddress_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ipAddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string ipAddress = 2;</code>
       * @return The bytes for ipAddress.
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        Object ref = ipAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ipAddress = 2;</code>
       * @param value The ipAddress to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddress(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ipAddress_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string ipAddress = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIpAddress() {
        ipAddress_ = getDefaultInstance().getIpAddress();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string ipAddress = 2;</code>
       * @param value The bytes for ipAddress to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ipAddress_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object sparkApp_ = "";
      /**
       * <code>string sparkApp = 3;</code>
       * @return The sparkApp.
       */
      public String getSparkApp() {
        Object ref = sparkApp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sparkApp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string sparkApp = 3;</code>
       * @return The bytes for sparkApp.
       */
      public com.google.protobuf.ByteString
          getSparkAppBytes() {
        Object ref = sparkApp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sparkApp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sparkApp = 3;</code>
       * @param value The sparkApp to set.
       * @return This builder for chaining.
       */
      public Builder setSparkApp(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        sparkApp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string sparkApp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSparkApp() {
        sparkApp_ = getDefaultInstance().getSparkApp();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string sparkApp = 3;</code>
       * @param value The bytes for sparkApp to set.
       * @return This builder for chaining.
       */
      public Builder setSparkAppBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sparkApp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private Object sessionId_ = "";
      /**
       * <code>string sessionId = 4;</code>
       * @return The sessionId.
       */
      public String getSessionId() {
        Object ref = sessionId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string sessionId = 4;</code>
       * @return The bytes for sessionId.
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sessionId = 4;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        sessionId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        sessionId_ = getDefaultInstance().getSessionId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 4;</code>
       * @param value The bytes for sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sessionId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private Object thriftHost_ = "";
      /**
       * <code>string thriftHost = 5;</code>
       * @return The thriftHost.
       */
      public String getThriftHost() {
        Object ref = thriftHost_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          thriftHost_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string thriftHost = 5;</code>
       * @return The bytes for thriftHost.
       */
      public com.google.protobuf.ByteString
          getThriftHostBytes() {
        Object ref = thriftHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          thriftHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string thriftHost = 5;</code>
       * @param value The thriftHost to set.
       * @return This builder for chaining.
       */
      public Builder setThriftHost(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        thriftHost_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string thriftHost = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearThriftHost() {
        thriftHost_ = getDefaultInstance().getThriftHost();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string thriftHost = 5;</code>
       * @param value The bytes for thriftHost to set.
       * @return This builder for chaining.
       */
      public Builder setThriftHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        thriftHost_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int thriftPort_ ;
      /**
       * <code>int32 thriftPort = 6;</code>
       * @return The thriftPort.
       */
      @Override
      public int getThriftPort() {
        return thriftPort_;
      }
      /**
       * <code>int32 thriftPort = 6;</code>
       * @param value The thriftPort to set.
       * @return This builder for chaining.
       */
      public Builder setThriftPort(int value) {

        thriftPort_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 thriftPort = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearThriftPort() {
        bitField0_ = (bitField0_ & ~0x00000020);
        thriftPort_ = 0;
        onChanged();
        return this;
      }

      private Object groupId_ = "";
      /**
       * <code>string groupId = 7;</code>
       * @return The groupId.
       */
      public String getGroupId() {
        Object ref = groupId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string groupId = 7;</code>
       * @return The bytes for groupId.
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string groupId = 7;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        groupId_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string groupId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        groupId_ = getDefaultInstance().getGroupId();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string groupId = 7;</code>
       * @param value The bytes for groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        groupId_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private Object statement_ = "";
      /**
       * <code>string statement = 8;</code>
       * @return The statement.
       */
      public String getStatement() {
        Object ref = statement_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          statement_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string statement = 8;</code>
       * @return The bytes for statement.
       */
      public com.google.protobuf.ByteString
          getStatementBytes() {
        Object ref = statement_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          statement_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string statement = 8;</code>
       * @param value The statement to set.
       * @return This builder for chaining.
       */
      public Builder setStatement(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        statement_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string statement = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatement() {
        statement_ = getDefaultInstance().getStatement();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string statement = 8;</code>
       * @param value The bytes for statement to set.
       * @return This builder for chaining.
       */
      public Builder setStatementBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        statement_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private Object state_ = "";
      /**
       * <code>string state = 9;</code>
       * @return The state.
       */
      public String getState() {
        Object ref = state_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string state = 9;</code>
       * @return The bytes for state.
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string state = 9;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        state_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string state = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        state_ = getDefaultInstance().getState();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string state = 9;</code>
       * @param value The bytes for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        state_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private Object plan_ = "";
      /**
       * <code>string plan = 10;</code>
       * @return The plan.
       */
      public String getPlan() {
        Object ref = plan_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          plan_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string plan = 10;</code>
       * @return The bytes for plan.
       */
      public com.google.protobuf.ByteString
          getPlanBytes() {
        Object ref = plan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          plan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string plan = 10;</code>
       * @param value The plan to set.
       * @return This builder for chaining.
       */
      public Builder setPlan(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        plan_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>string plan = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlan() {
        plan_ = getDefaultInstance().getPlan();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>string plan = 10;</code>
       * @param value The bytes for plan to set.
       * @return This builder for chaining.
       */
      public Builder setPlanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        plan_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private Object error_ = "";
      /**
       * <code>string error = 11;</code>
       * @return The error.
       */
      public String getError() {
        Object ref = error_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string error = 11;</code>
       * @return The bytes for error.
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error = 11;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        error_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>string error = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        error_ = getDefaultInstance().getError();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>string error = 11;</code>
       * @param value The bytes for error to set.
       * @return This builder for chaining.
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        error_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>int64 startTime = 12;</code>
       * @return The startTime.
       */
      @Override
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>int64 startTime = 12;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(long value) {

        startTime_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>int64 startTime = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000800);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long finishTimestamp_ ;
      /**
       * <code>int64 finishTimestamp = 13;</code>
       * @return The finishTimestamp.
       */
      @Override
      public long getFinishTimestamp() {
        return finishTimestamp_;
      }
      /**
       * <code>int64 finishTimestamp = 13;</code>
       * @param value The finishTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setFinishTimestamp(long value) {

        finishTimestamp_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>int64 finishTimestamp = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearFinishTimestamp() {
        bitField0_ = (bitField0_ & ~0x00001000);
        finishTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private long duration_ ;
      /**
       * <code>int64 duration = 14;</code>
       * @return The duration.
       */
      @Override
      public long getDuration() {
        return duration_;
      }
      /**
       * <code>int64 duration = 14;</code>
       * @param value The duration to set.
       * @return This builder for chaining.
       */
      public Builder setDuration(long value) {

        duration_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <code>int64 duration = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00002000);
        duration_ = 0L;
        onChanged();
        return this;
      }

      private Object durationFormatted_ = "";
      /**
       * <code>string durationFormatted = 15;</code>
       * @return The durationFormatted.
       */
      public String getDurationFormatted() {
        Object ref = durationFormatted_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          durationFormatted_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string durationFormatted = 15;</code>
       * @return The bytes for durationFormatted.
       */
      public com.google.protobuf.ByteString
          getDurationFormattedBytes() {
        Object ref = durationFormatted_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          durationFormatted_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string durationFormatted = 15;</code>
       * @param value The durationFormatted to set.
       * @return This builder for chaining.
       */
      public Builder setDurationFormatted(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        durationFormatted_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <code>string durationFormatted = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearDurationFormatted() {
        durationFormatted_ = getDefaultInstance().getDurationFormatted();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
        return this;
      }
      /**
       * <code>string durationFormatted = 15;</code>
       * @param value The bytes for durationFormatted to set.
       * @return This builder for chaining.
       */
      public Builder setDurationFormattedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        durationFormatted_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.viettel.bi.spark.thrift.SparkQueryResult)
    }

    // @@protoc_insertion_point(class_scope:com.viettel.bi.spark.thrift.SparkQueryResult)
    private static final SparkQueryResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SparkQueryResult();
    }

    public static SparkQueryResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SparkQueryResult>
        PARSER = new com.google.protobuf.AbstractParser<SparkQueryResult>() {
      @Override
      public SparkQueryResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SparkQueryResult> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SparkQueryResult> getParserForType() {
      return PARSER;
    }

    @Override
    public SparkQueryResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_viettel_bi_spark_thrift_SparkQueryResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_viettel_bi_spark_thrift_SparkQueryResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030spark_query_result.proto\022\033com.viettel." +
      "bi.spark.thrift\"\255\002\n\020SparkQueryResult\022\020\n\010" +
      "username\030\001 \001(\t\022\021\n\tipAddress\030\002 \001(\t\022\020\n\010spa" +
      "rkApp\030\003 \001(\t\022\021\n\tsessionId\030\004 \001(\t\022\022\n\nthrift" +
      "Host\030\005 \001(\t\022\022\n\nthriftPort\030\006 \001(\005\022\017\n\007groupI" +
      "d\030\007 \001(\t\022\021\n\tstatement\030\010 \001(\t\022\r\n\005state\030\t \001(" +
      "\t\022\014\n\004plan\030\n \001(\t\022\r\n\005error\030\013 \001(\t\022\021\n\tstartT" +
      "ime\030\014 \001(\003\022\027\n\017finishTimestamp\030\r \001(\003\022\020\n\010du" +
      "ration\030\016 \001(\003\022\031\n\021durationFormatted\030\017 \001(\tB" +
      "\031B\027SparkQueryResultMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_viettel_bi_spark_thrift_SparkQueryResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_viettel_bi_spark_thrift_SparkQueryResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_viettel_bi_spark_thrift_SparkQueryResult_descriptor,
        new String[] { "Username", "IpAddress", "SparkApp", "SessionId", "ThriftHost", "ThriftPort", "GroupId", "Statement", "State", "Plan", "Error", "StartTime", "FinishTimestamp", "Duration", "DurationFormatted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
